services:
  # Base de datos PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: company-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: admin_portal
      POSTGRES_USER: jcuadrado
      POSTGRES_PASSWORD: jcuadrado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - company-network

  # Backend Spring Boot
  company-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-db
    networks:
      - company-network

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
    driver: local

# Red personalizada
networks:
  company-network:
    driver: bridge
